### 0. EDA (*)
In the whole exercise, we will work with the "mpg" dataset from seaborn dataset. Start by loading dataset "mpg" from the load_dataset method in seaborn module. The goal will be to use linear regression to predict mpg - miles per gallon.

  a) Start by doing some initial EDA such as info(), describe() and figure out what you want to do with the missing values.

  b) Use describe only on those columns that are relevant to get statistical information from.

  c) Make some plots on some of the columns that you find interesting.

  d) Check if there are any columns you might want to drop.

In [26]:
from seaborn import load_dataset

df = load_dataset("mpg").set_index('name')
df.head()

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0       130.0    3504   
buick skylark 320          15.0          8         350.0       165.0    3693   
plymouth satellite         18.0          8         318.0       150.0    3436   
amc rebel sst              16.0          8         304.0       150.0    3433   
ford torino                17.0          8         302.0       140.0    3449   

                           acceleration  model_year origin  
name                                                        
chevrolet chevelle malibu          12.0          70    usa  
buick skylark 320                  11.5          70    usa  
plymouth satellite                 11.0          70    usa  
amc rebel sst                      12.0          70    usa  
ford torino                        10.5          70    usa

In [27]:
df.shape

(398, 8)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 398 entries, chevrolet chevelle malibu to chevy s-10
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 28.0+ KB


In [29]:
df.head(10)

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0       130.0    3504   
buick skylark 320          15.0          8         350.0       165.0    3693   
plymouth satellite         18.0          8         318.0       150.0    3436   
amc rebel sst              16.0          8         304.0       150.0    3433   
ford torino                17.0          8         302.0       140.0    3449   
ford galaxie 500           15.0          8         429.0       198.0    4341   
chevrolet impala           14.0          8         454.0       220.0    4354   
plymouth fury iii          14.0          8         440.0       215.0    4312   
pontiac catalina           14.0          8         455.0       225.0    4425   
amc ambassador dpl         15.0          8         390.0       190.0    3850   

                           acceleration  model_year origin  
name                                                        
chevrolet chevelle malibu          12.0          70    usa  
buick skylark 320                  11.5          70    usa  
plymouth satellite                 11.0          70    usa  
amc rebel sst                      12.0          70    usa  
ford torino                        10.5          70    usa  
ford galaxie 500                   10.0          70    usa  
chevrolet impala                    9.0          70    usa  
plymouth fury iii                   8.5          70    usa  
pontiac catalina                   10.0          70    usa  
amc ambassador dpl                  8.5          70    usa

In [30]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [31]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

### dealing with missing values

Since all missing values are all under 'horsepower', and those are all well documented in different libraries, I chose to assign them 'manualy'

In [32]:
df_missing_values = df[df["horsepower"].isnull()]
df_missing_values

mpg  cylinders  displacement  horsepower  weight  \
name                                                                      
ford pinto            25.0          4          98.0         NaN    2046   
ford maverick         21.0          6         200.0         NaN    2875   
renault lecar deluxe  40.9          4          85.0         NaN    1835   
ford mustang cobra    23.6          4         140.0         NaN    2905   
renault 18i           34.5          4         100.0         NaN    2320   
amc concord dl        23.0          4         151.0         NaN    3035   

                      acceleration  model_year  origin  
name                                                    
ford pinto                    19.0          71     usa  
ford maverick                 17.0          74     usa  
renault lecar deluxe          17.3          80  europe  
ford mustang cobra            14.3          80     usa  
renault 18i                   15.8          81  europe  
amc concord dl                20.5          82     usa

In [33]:
# assign values
replacement_values = [75.0, 75.0, 50.0, 132.0, 51.0, 82.0]

for index, replacement_values in zip(df_missing_values.index, replacement_values):
    df.at[index, "horsepower"] = replacement_values


In [34]:
replaced_rows = df[df.index.isin(df_missing_values.index)]

replaced_rows

mpg  cylinders  displacement  horsepower  weight  \
name                                                                      
ford maverick         21.0          6         200.0        75.0    2587   
ford pinto            25.0          4          98.0        75.0    2046   
ford maverick         18.0          6         250.0        75.0    3021   
ford pinto            19.0          4         122.0        75.0    2310   
ford maverick         21.0          6         200.0        75.0    2875   
ford pinto            26.0          4         122.0        75.0    2451   
ford maverick         15.0          6         250.0        75.0    3158   
ford pinto            23.0          4         140.0        75.0    2639   
ford pinto            18.0          6         171.0        75.0    2984   
ford maverick         24.0          6         200.0        75.0    3012   
ford pinto            26.5          4         140.0        75.0    2565   
renault lecar deluxe  40.9          4          85.0        50.0    1835   
ford mustang cobra    23.6          4         140.0       132.0    2905   
renault 18i           34.5          4         100.0        51.0    2320   
amc concord dl        23.0          4         151.0        82.0    3035   

                      acceleration  model_year  origin  
name                                                    
ford maverick                 16.0          70     usa  
ford pinto                    19.0          71     usa  
ford maverick                 16.5          73     usa  
ford pinto                    18.5          73     usa  
ford maverick                 17.0          74     usa  
ford pinto                    16.5          74     usa  
ford maverick                 19.5          75     usa  
ford pinto                    17.0          75     usa  
ford pinto                    14.5          75     usa  
ford maverick                 17.6          76     usa  
ford pinto                    13.6          76     usa  
renault lecar deluxe          17.3          80  europe  
ford mustang cobra            14.3          80     usa  
renault 18i                   15.8          81  europe  
amc concord dl                20.5          82     usa

## Train|test split

Features and label

In [35]:
# defining X matrix (features) and y labels
X, y = df.drop(["mpg", "acceleration", "model_year", "origin"], axis="columns"), df["mpg"]

X

cylinders  displacement  horsepower  weight
name                                                                  
chevrolet chevelle malibu          8         307.0       130.0    3504
buick skylark 320                  8         350.0       165.0    3693
plymouth satellite                 8         318.0       150.0    3436
amc rebel sst                      8         304.0       150.0    3433
ford torino                        8         302.0       140.0    3449
...                              ...           ...         ...     ...
ford mustang gl                    4         140.0        86.0    2790
vw pickup                          4          97.0        52.0    2130
dodge rampage                      4         135.0        84.0    2295
ford ranger                        4         120.0        79.0    2625
chevy s-10                         4         119.0        82.0    2720

[398 rows x 4 columns]

In [36]:
y

name
chevrolet chevelle malibu    18.0
buick skylark 320            15.0
plymouth satellite           18.0
amc rebel sst                16.0
ford torino                  17.0
                             ... 
ford mustang gl              27.0
vw pickup                    44.0
dodge rampage                32.0
ford ranger                  28.0
chevy s-10                   31.0
Name: mpg, Length: 398, dtype: float64

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"{X_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_train.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (318, 4)
X_test.shape = (80, 4)
y_train.shape = (318,)
y_test.shape = (80,)


In [38]:
X_test.head()

cylinders  displacement  horsepower  weight
name                                                                   
honda civic                         4          91.0        53.0    1795
ford ranger                         4         120.0        79.0    2625
amc gremlin                         6         232.0       100.0    2634
plymouth volare premier v8          8         318.0       150.0    3940
plymouth fury gran sedan            8         318.0       150.0    4237

In [39]:
X_train.head()

cylinders  displacement  horsepower  weight
name                                                           
amc rebel sst               8         304.0       150.0    3433
datsun pl510                4          97.0        88.0    2130
mazda glc custom l          4          91.0        68.0    2025
honda civic cvcc            4          91.0        60.0    1800
audi 100ls                  4         115.0        95.0    2694

## Feature Scaling

Normalization

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

MinMaxScaler()

In [41]:
scaled_X_train = scaler.transform(X_train)

scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.shape = }")
print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")

scaled_X_train.shape = (318, 4)
scaled_X_train.min() = 0.0
scaled_X_train.max() = 1.0


In [42]:
print(f"{scaled_X_test.shape = }")
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_test.shape = (80, 4)
scaled_X_test.min() = 0.03351955307262572
scaled_X_test.max() = 1.0279329608938548


## Fit algorithm (Lineear Regression) to training data

In [43]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(scaled_X_train, y_train)
print(f"{model.intercept_ = }")
print(f"{model.coef_ = }")

model.intercept_ = 34.251225757260684
model.coef_ = array([ -1.07076361,  -1.94728576,  -7.4811019 , -18.54357589])


In [44]:
scaled_X_test[0]

array([0.2       , 0.05943152, 0.03910615, 0.05160193])

In [45]:
test_samples_features = scaled_X_test[0]
test_samples_label = y_test.values[0]

print(f"{test_samples_features = }")
print(f"{test_samples_label = }")

model.predict(test_samples_features.reshape(1,-1))

test_samples_features = array([0.2       , 0.05943152, 0.03910615, 0.05160193])
test_samples_label = 33.0


array([32.67190155])

## Predict on test data

In [46]:
y_pred = model.predict(scaled_X_test)
y_pred

array([32.67190155, 27.07552754, 25.1586769 , 15.34151476, 13.78000582,
       29.57535599, 25.16974696,  7.83124382, 16.67419795, 25.0974564 ,
       13.78065895, 31.19299444, 31.1201889 , 15.66432429, 27.57844937,
        8.42416535, 27.12789861, 21.80067219, 12.20296597, 31.12491254,
       27.79524446, 24.49246203, 23.60037174, 29.91073372, 18.52505743,
       30.92220697, 28.61923155, 25.93877395, 20.11207205,  9.1395686 ,
       25.81483059, 30.75112884, 16.43564975, 28.26643715, 31.01783018,
        9.80833157, 26.10529645, 18.32356381, 12.40777069, 29.15363848,
       24.48163996, 32.14410739, 24.07195563,  8.86469622, 26.94889306,
       29.14416948, 29.25546261, 25.32406677, 27.8017351 , 29.67438841,
       28.40835015, 31.24916484, 29.19479526, 10.72299094, 24.55916914,
       11.12907947, 15.13018142, 26.09319647, 28.41315582, 22.09057676,
       15.37778214, 32.67190155, 27.0684616 , 24.87998414, 24.11917202,
       28.52931745, 25.45953087, 30.82075147, 30.4040657 , 15.40

## Evaluate Performace

In [50]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# MAE
mean_absolute_error(y_test, y_pred)

3.1279623769477864

In [52]:
# MSE
mean_squared_error(y_test, y_pred)

14.74636016872791

In [53]:
# RMSE
import numpy as np
np.sqrt(mean_squared_error(y_test, y_pred))

3.840098979027482